### ISSUE TITLE
xindex-uca does not sort correctly then @ is used for "forced" sorting

### ISSUE THREAD

**Issue by Sveinung58** [michal-h21/lua-uca#1]
In Norwegian (and Danish) double "a" (AA, Aa, aa) was previously used to substitute the letter Å. Totay many Norwegian still spell their name using "aa" instead of Å. So very often "aa" shall be sorted as "å" as the last letter in the alphabet. However, sometimes double "a" shall be sorted as two "a", based on pronunciation, for example the English name "Aaron"  (Aron in Norwegian). This name should be sorted as the under "A" as one of the first (Aa). On the other side, the Norwegian name Aage, (Åge), should be sorted under "Å". If you try to "force" sorting by giving sorting order, "Aaron\index{Aron@Aaron}, using "xindex-uca", "Aaaron is sorted under "Å" after "A" but before "B". 

The same is goes for the the letters "Oe" which sometimes is a substitute for Norwegian "Ø" or German (and Swedish) "Ö".  You have the name "Oehlensläger", which should be sorted as "Öhlenschläger" or "Øhlenschläger". It ends up under a new "O", after "Æ", before "Ø".

If I choose "xindex-norsk" (from you answer on Stackexchange https://tex.stackexchange.com/a/524014/9632), it is sorted differently. "Aage" ends ups under a dublicated "A" between two "Å". "Oehlensläger" and "Aaron" is sorted correctly.

**Comment by Sveinung58** [comment]
Here is the indexed words that created the issues:

Anemone\index{Anemone|(}
Anemone\index{Anemone}
Anemone\index{Anemone}
Aaron\index{A1ron@Aaron}
Aage\index{Aage}
Oen\index{Oen}
Oelenschläger\index{Ølenschläger@Oelenschläger}
Åberget\index{Åberget}
Östermalm\index{Östermalm}
Àctomere\index{Àctomere}

**Comment by michal-h21** [comment]
Thanks for spotting this, it should be fixed now.
